### ISSUE TITLE
Activating extension 'paulmolluzzo.convert-css-in-js' fails in vscode.

### ISSUE THREAD

**Issue by evankyle** [ansumanshah/css-in-js#23] opened 2018-06-29 18:55 UTC
css-in-js 1.1.1
vscode version 1.24.1
shell 1.7.12
renderer 58.0.3029.110
node 7.9.0
windows 10
no other extensions running.

```
console.ts:136 [Extension Host] Activating extension `paulmolluzzo.convert-css-in-js` failed:  Cannot read property 'properties' of undefined
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

**Comment by paulmolluzzo** [comment] 2018-06-29 19:30
Published a fix 2 minutes ago. Please check that it works. 🙏 🙌

**Comment by paulmolluzzo** [comment] 2018-06-29 19:32
Also, thank you very much for the bug report!

**Comment by evankyle** [comment] 2018-06-29 20:40
I updated to 1.1.2 restart and same error.

Maybe this stack is more useful.

```
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'properties' of undefined
	at Object.<anonymous> (C:\Users\evank\.vscode\extensions\paulmolluzzo.convert-css-in-js-1.1.2\dist\autocomplete.js:12:46)
	at Object.<anonymous> (C:\Users\evank\.vscode\extensions\paulmolluzzo.convert-css-in-js-1.1.2\dist\autocomplete.js:170:3)
```

**Comment by paulmolluzzo** [comment] 2018-07-02 01:55
Thanks again! The issue is related to the `css-in-js-helpers` package. For some reason it's published without the required completion JSON files, and those are the `properties` being referred to in `TypeError: Cannot read property 'properties' of undefined`.

I published `v1.1.3`. I just installed it and it seems to work, but if you can give it a shot @evankyle I'd really appreciate it. If this one works I'll make a PR with these fixes so we can at least having a stable version on `master`. 🤞

**Comment by evankyle** [comment] 2018-07-02 02:20
It no longer fails starting up and I now see hints for properties in my JSS objects so I think it works! However I can't say for sure as I'm not getting hints for property values. e.g. textAlign: '...', does not give a hint of center, left, right, etc. I have never used this tool so I don't know if this implemented. Thank you very much!

**Comment by paulmolluzzo** [comment] 2018-07-02 02:24
> However I can't say for sure as I'm not getting hints for property values. e.g. textAlign: '...', does not give a hint of center, left, right, etc.

I don’t know off hand either, but would expect that to be in there for sure. I think the `css-in-js-helpers` package needs some ❤️  before we can make sure all that is working entirely.

Any ideas @ansumanshah?

Closing this issue in the meantime, and I think we can close #22 and others as well. Sorry all for the issues. 🙊

**Closed as completed by paulmolluzzo** 2018-07-02 02:24 UTC
Labels: bug

**Comment by evankyle** [comment] 2018-07-02 02:31
I should have tested a little more as I had a typo on the property I used to test values! alighItems , it works fine with alignItems !!! Sorry
